// <auto-generated />
using System;
using Hood.Web;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hood.Development.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Hood.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address1");

                    b.Property<string>("Address2");

                    b.Property<string>("City")
                        .IsRequired();

                    b.Property<string>("ContactName");

                    b.Property<string>("Country")
                        .IsRequired();

                    b.Property<string>("County")
                        .IsRequired();

                    b.Property<double>("Latitude")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("0.0");

                    b.Property<double>("Longitude")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("0.0");

                    b.Property<string>("Number")
                        .IsRequired();

                    b.Property<string>("Postcode")
                        .IsRequired();

                    b.Property<string>("QuickName");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("HoodAddresses");
                });

            modelBuilder.Entity("Hood.Models.ApiEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Action");

                    b.Property<string>("ApiKeyId");

                    b.Property<string>("IpAddress");

                    b.Property<int>("RequiredAccessLevel");

                    b.Property<string>("RouteDataJson");

                    b.Property<DateTime>("Time");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("ApiKeyId");

                    b.ToTable("HoodApiEvents");
                });

            modelBuilder.Entity("Hood.Models.ApiKey", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessLevel");

                    b.Property<bool>("Active");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Key");

                    b.Property<string>("Name");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("HoodApiKeys");
                });

            modelBuilder.Entity("Hood.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<bool>("Active");

                    b.Property<bool>("Anonymous");

                    b.Property<string>("AvatarJson");

                    b.Property<string>("BillingAddressJson");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("DeliveryAddressJson");

                    b.Property<string>("DisplayName");

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FirstName");

                    b.Property<DateTime>("LastLogOn");

                    b.Property<string>("LastLoginIP");

                    b.Property<string>("LastLoginLocation");

                    b.Property<string>("LastName");

                    b.Property<string>("Latitude");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("Longitude");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<string>("StripeId");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.Property<string>("UserVars");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Hood.Models.Content", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AllowComments");

                    b.Property<string>("AuthorId");

                    b.Property<string>("Body");

                    b.Property<string>("ContentType");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Excerpt")
                        .IsRequired();

                    b.Property<bool>("Featured");

                    b.Property<string>("FeaturedImageJson");

                    b.Property<string>("LastEditedBy");

                    b.Property<DateTime>("LastEditedOn");

                    b.Property<string>("Notes");

                    b.Property<int?>("ParentId");

                    b.Property<bool>("Public");

                    b.Property<DateTime>("PublishDate");

                    b.Property<int>("ShareCount");

                    b.Property<string>("ShareImageJson");

                    b.Property<string>("Slug");

                    b.Property<int>("Status");

                    b.Property<string>("SystemNotes");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<string>("UserVars");

                    b.Property<int>("Views");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("HoodContent");
                });

            modelBuilder.Entity("Hood.Models.ContentCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ContentCategoryId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContentType");

                    b.Property<string>("DisplayName");

                    b.Property<int?>("ParentCategoryId");

                    b.Property<string>("Slug");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("HoodContentCategories");
                });

            modelBuilder.Entity("Hood.Models.ContentCategoryJoin", b =>
                {
                    b.Property<int>("ContentId");

                    b.Property<int>("CategoryId");

                    b.HasKey("ContentId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("HoodContentCategoryJoins");
                });

            modelBuilder.Entity("Hood.Models.ContentMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BlobReference");

                    b.Property<int>("ContentId");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<long>("FileSize");

                    b.Property<string>("FileType");

                    b.Property<string>("Filename");

                    b.Property<int>("GenericFileType");

                    b.Property<string>("LargeUrl");

                    b.Property<string>("MediumUrl");

                    b.Property<string>("Path")
                        .HasColumnName("Directory");

                    b.Property<string>("SmallUrl");

                    b.Property<string>("ThumbUrl");

                    b.Property<string>("UniqueId");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("ContentId");

                    b.ToTable("HoodContentMedia");
                });

            modelBuilder.Entity("Hood.Models.ContentMeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BaseValue");

                    b.Property<int>("ContentId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.HasAlternateKey("ContentId", "Name");

                    b.ToTable("HoodContentMetadata");
                });

            modelBuilder.Entity("Hood.Models.Forum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuthorDisplayName");

                    b.Property<string>("AuthorId");

                    b.Property<string>("AuthorName");

                    b.Property<string>("AuthorRoles");

                    b.Property<string>("Body");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<bool>("Featured");

                    b.Property<string>("FeaturedImageJson");

                    b.Property<string>("LastEditedBy");

                    b.Property<DateTime>("LastEditedOn");

                    b.Property<long?>("LastPostId");

                    b.Property<DateTime?>("LastPosted");

                    b.Property<int?>("LastTopicId");

                    b.Property<string>("LastUserDisplayName");

                    b.Property<string>("LastUserId");

                    b.Property<string>("LastUserName");

                    b.Property<int>("ModeratedPostCount");

                    b.Property<string>("Notes");

                    b.Property<int>("NumPosts");

                    b.Property<int>("NumTopics");

                    b.Property<bool>("PostingRequiresLogin");

                    b.Property<string>("PostingRoles");

                    b.Property<string>("PostingSubscriptions");

                    b.Property<bool>("Published");

                    b.Property<bool>("RequirePostModeration");

                    b.Property<bool>("RequireTopicModeration");

                    b.Property<int>("ShareCount");

                    b.Property<string>("ShareImageJson");

                    b.Property<string>("Slug");

                    b.Property<string>("SystemNotes");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<string>("UserVars");

                    b.Property<bool>("ViewingRequiresLogin");

                    b.Property<string>("ViewingRoles");

                    b.Property<string>("ViewingSubscriptions");

                    b.Property<int>("Views");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("HoodForums");
                });

            modelBuilder.Entity("Hood.Models.ForumCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ForumCategoryId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DisplayName");

                    b.Property<int?>("ParentCategoryId");

                    b.Property<string>("Slug");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("HoodForumCategories");
                });

            modelBuilder.Entity("Hood.Models.ForumCategoryJoin", b =>
                {
                    b.Property<int>("ForumId");

                    b.Property<int>("CategoryId");

                    b.HasKey("ForumId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("HoodForumCategoryJoins");
                });

            modelBuilder.Entity("Hood.Models.Log", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Detail");

                    b.Property<string>("Source");

                    b.Property<string>("SourceUrl");

                    b.Property<DateTime>("Time");

                    b.Property<string>("Title");

                    b.Property<int>("Type");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("HoodLogs");
                });

            modelBuilder.Entity("Hood.Models.MediaDirectory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DisplayName");

                    b.Property<string>("OwnerId");

                    b.Property<int?>("ParentId");

                    b.Property<string>("Slug");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("HoodMediaDirectories");
                });

            modelBuilder.Entity("Hood.Models.MediaObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BlobReference");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<int?>("DirectoryId");

                    b.Property<long>("FileSize");

                    b.Property<string>("FileType");

                    b.Property<string>("Filename");

                    b.Property<int>("GenericFileType");

                    b.Property<string>("LargeUrl");

                    b.Property<string>("MediumUrl");

                    b.Property<string>("Path")
                        .HasColumnName("Directory");

                    b.Property<string>("SmallUrl");

                    b.Property<string>("ThumbUrl");

                    b.Property<string>("UniqueId");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("DirectoryId");

                    b.ToTable("HoodMedia");
                });

            modelBuilder.Entity("Hood.Models.Option", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("HoodOptions");
                });

            modelBuilder.Entity("Hood.Models.Post", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Approved");

                    b.Property<DateTime?>("ApprovedTime");

                    b.Property<string>("AuthorDisplayName");

                    b.Property<string>("AuthorId");

                    b.Property<string>("AuthorIp");

                    b.Property<string>("AuthorName");

                    b.Property<string>("AuthorRoles");

                    b.Property<string>("Body")
                        .IsRequired();

                    b.Property<string>("DeleteReason");

                    b.Property<bool>("Deleted");

                    b.Property<string>("DeletedById");

                    b.Property<DateTime?>("DeletedTime");

                    b.Property<string>("EditReason");

                    b.Property<bool>("Edited");

                    b.Property<string>("EditedById");

                    b.Property<DateTime?>("EditedTime");

                    b.Property<DateTime>("PostedTime");

                    b.Property<long?>("ReplyId");

                    b.Property<string>("Signature");

                    b.Property<int>("TopicId");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("DeletedById");

                    b.HasIndex("EditedById");

                    b.HasIndex("ReplyId");

                    b.HasIndex("TopicId");

                    b.ToTable("HoodForumPosts");
                });

            modelBuilder.Entity("Hood.Models.PropertyFloorplan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BlobReference");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<long>("FileSize");

                    b.Property<string>("FileType");

                    b.Property<string>("Filename");

                    b.Property<int>("GenericFileType");

                    b.Property<string>("LargeUrl");

                    b.Property<string>("MediumUrl");

                    b.Property<string>("Path")
                        .HasColumnName("Directory");

                    b.Property<int>("PropertyId");

                    b.Property<string>("SmallUrl");

                    b.Property<string>("ThumbUrl");

                    b.Property<string>("UniqueId");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("HoodPropertyFloorplans");
                });

            modelBuilder.Entity("Hood.Models.PropertyListing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Additional");

                    b.Property<string>("Address1");

                    b.Property<string>("Address2");

                    b.Property<string>("Addressee");

                    b.Property<string>("AgentId");

                    b.Property<string>("AgentInfo");

                    b.Property<bool>("AllowComments");

                    b.Property<string>("Areas");

                    b.Property<decimal?>("AskingPrice");

                    b.Property<string>("AskingPriceDisplay");

                    b.Property<int>("Bedrooms");

                    b.Property<string>("City");

                    b.Property<bool>("Confidential");

                    b.Property<string>("ContactName");

                    b.Property<string>("Country");

                    b.Property<string>("County");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description");

                    b.Property<string>("Email");

                    b.Property<bool>("Featured");

                    b.Property<string>("FeaturedImageJson");

                    b.Property<decimal?>("Fees");

                    b.Property<string>("FeesDisplay");

                    b.Property<string>("Floors");

                    b.Property<string>("InfoDownloadJson");

                    b.Property<string>("LastEditedBy");

                    b.Property<DateTime>("LastEditedOn");

                    b.Property<double>("Latitude")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("0.0");

                    b.Property<string>("Lease");

                    b.Property<string>("LeaseStatus");

                    b.Property<string>("ListingType");

                    b.Property<string>("Location");

                    b.Property<double>("Longitude")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("0.0");

                    b.Property<string>("Notes");

                    b.Property<string>("Number");

                    b.Property<string>("Phone");

                    b.Property<string>("Planning");

                    b.Property<string>("Postcode");

                    b.Property<decimal?>("Premium");

                    b.Property<string>("PremiumDisplay");

                    b.Property<string>("PropertyType");

                    b.Property<bool>("Public");

                    b.Property<DateTime>("PublishDate");

                    b.Property<string>("QuickName");

                    b.Property<string>("Reference");

                    b.Property<decimal?>("Rent");

                    b.Property<string>("RentDisplay");

                    b.Property<int>("ShareCount");

                    b.Property<string>("ShortDescription");

                    b.Property<string>("Size");

                    b.Property<int>("Status");

                    b.Property<string>("SystemNotes");

                    b.Property<string>("Tags");

                    b.Property<string>("Title");

                    b.Property<string>("UserVars");

                    b.Property<int>("Views");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.ToTable("HoodProperties");
                });

            modelBuilder.Entity("Hood.Models.PropertyMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BlobReference");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<long>("FileSize");

                    b.Property<string>("FileType");

                    b.Property<string>("Filename");

                    b.Property<int>("GenericFileType");

                    b.Property<string>("LargeUrl");

                    b.Property<string>("MediumUrl");

                    b.Property<string>("Path")
                        .HasColumnName("Directory");

                    b.Property<int>("PropertyId");

                    b.Property<string>("SmallUrl");

                    b.Property<string>("ThumbUrl");

                    b.Property<string>("UniqueId");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("HoodPropertyMedia");
                });

            modelBuilder.Entity("Hood.Models.PropertyMeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BaseValue");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("PropertyId");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.HasAlternateKey("PropertyId", "Name");

                    b.ToTable("HoodPropertyMetadata");
                });

            modelBuilder.Entity("Hood.Models.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Addon");

                    b.Property<int>("Amount");

                    b.Property<string>("Colour");

                    b.Property<DateTime>("Created");

                    b.Property<string>("CreatedBy");

                    b.Property<string>("Currency");

                    b.Property<string>("Description");

                    b.Property<string>("FeaturedImageJson");

                    b.Property<string>("FeaturesJson");

                    b.Property<string>("Interval");

                    b.Property<int>("IntervalCount");

                    b.Property<string>("LastEditedBy");

                    b.Property<DateTime>("LastEditedOn");

                    b.Property<int>("Level");

                    b.Property<bool>("LiveMode");

                    b.Property<string>("Name");

                    b.Property<int>("NumberAllowed");

                    b.Property<bool>("Public");

                    b.Property<string>("StatementDescriptor");

                    b.Property<string>("StripeId");

                    b.Property<int?>("SubscriptionProductId");

                    b.Property<int?>("TrialPeriodDays");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionProductId");

                    b.ToTable("HoodSubscriptions");
                });

            modelBuilder.Entity("Hood.Models.SubscriptionFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BaseValue");

                    b.Property<string>("Name");

                    b.Property<int>("SubscriptionId");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("HoodSubscriptionFeatures");
                });

            modelBuilder.Entity("Hood.Models.SubscriptionProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Body");

                    b.Property<DateTime>("Created");

                    b.Property<string>("CreatedBy");

                    b.Property<string>("DisplayName");

                    b.Property<string>("FeaturedImageJson");

                    b.Property<string>("FeaturesJson");

                    b.Property<string>("LastEditedBy");

                    b.Property<DateTime>("LastEditedOn");

                    b.Property<bool>("Public");

                    b.Property<string>("Slug");

                    b.Property<string>("StripeId");

                    b.HasKey("Id");

                    b.ToTable("HoodSubscriptionGroups");
                });

            modelBuilder.Entity("Hood.Models.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AllowReplies");

                    b.Property<bool>("Approved");

                    b.Property<DateTime?>("ApprovedTime");

                    b.Property<string>("AuthorDisplayName");

                    b.Property<string>("AuthorId");

                    b.Property<string>("AuthorName");

                    b.Property<string>("AuthorRoles");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<bool>("Featured");

                    b.Property<string>("FeaturedImageJson");

                    b.Property<int>("ForumId");

                    b.Property<string>("LastEditedBy");

                    b.Property<DateTime>("LastEditedOn");

                    b.Property<long?>("LastPostId");

                    b.Property<DateTime?>("LastPosted");

                    b.Property<int?>("LastTopicId");

                    b.Property<string>("LastUserDisplayName");

                    b.Property<string>("LastUserId");

                    b.Property<string>("LastUserName");

                    b.Property<int>("ModeratedPostCount");

                    b.Property<string>("Notes");

                    b.Property<int>("NumPosts");

                    b.Property<bool>("PostingRequiresLogin");

                    b.Property<string>("PostingRoles");

                    b.Property<string>("PostingSubscriptions");

                    b.Property<bool>("Published");

                    b.Property<int>("ShareCount");

                    b.Property<string>("ShareImageJson");

                    b.Property<string>("SystemNotes");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<string>("UserVars");

                    b.Property<bool>("ViewingRequiresLogin");

                    b.Property<string>("ViewingRoles");

                    b.Property<string>("ViewingSubscriptions");

                    b.Property<int>("Views");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ForumId");

                    b.ToTable("HoodForumTopics");
                });

            modelBuilder.Entity("Hood.Models.UserAccessCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code");

                    b.Property<DateTime>("DateUsed");

                    b.Property<DateTime>("Expiry");

                    b.Property<string>("Type");

                    b.Property<bool>("Used");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserAccessCodes");
                });

            modelBuilder.Entity("Hood.Models.UserSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("UserSubscriptionId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("CancelAtPeriodEnd");

                    b.Property<DateTime?>("CanceledAt");

                    b.Property<bool>("Confirmed");

                    b.Property<DateTime?>("Created");

                    b.Property<DateTime?>("CurrentPeriodEnd");

                    b.Property<DateTime?>("CurrentPeriodStart");

                    b.Property<string>("CustomerId");

                    b.Property<bool>("Deleted");

                    b.Property<DateTime>("DeletedAt");

                    b.Property<DateTime?>("EndedAt");

                    b.Property<DateTime>("LastUpdated");

                    b.Property<string>("Notes");

                    b.Property<long>("Quantity");

                    b.Property<DateTime?>("Start");

                    b.Property<string>("Status");

                    b.Property<string>("StripeId");

                    b.Property<int>("SubscriptionId");

                    b.Property<decimal?>("TaxPercent");

                    b.Property<DateTime?>("TrialEnd");

                    b.Property<DateTime?>("TrialStart");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("UserId");

                    b.ToTable("HoodUserSubscriptions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Hood.Models.Address", b =>
                {
                    b.HasOne("Hood.Models.ApplicationUser", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Hood.Models.ApiEvent", b =>
                {
                    b.HasOne("Hood.Models.ApiKey", "ApiKey")
                        .WithMany("Events")
                        .HasForeignKey("ApiKeyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Hood.Models.ApiKey", b =>
                {
                    b.HasOne("Hood.Models.ApplicationUser", "User")
                        .WithMany("ApiKeys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Hood.Models.Content", b =>
                {
                    b.HasOne("Hood.Models.ApplicationUser", "Author")
                        .WithMany("Content")
                        .HasForeignKey("AuthorId");
                });

            modelBuilder.Entity("Hood.Models.ContentCategory", b =>
                {
                    b.HasOne("Hood.Models.ContentCategory", "ParentCategory")
                        .WithMany("Children")
                        .HasForeignKey("ParentCategoryId");
                });

            modelBuilder.Entity("Hood.Models.ContentCategoryJoin", b =>
                {
                    b.HasOne("Hood.Models.ContentCategory", "Category")
                        .WithMany("Content")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Hood.Models.Content", "Content")
                        .WithMany("Categories")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Hood.Models.ContentMedia", b =>
                {
                    b.HasOne("Hood.Models.Content", "Content")
                        .WithMany("Media")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Hood.Models.ContentMeta", b =>
                {
                    b.HasOne("Hood.Models.Content", "Content")
                        .WithMany("Metadata")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Hood.Models.Forum", b =>
                {
                    b.HasOne("Hood.Models.ApplicationUser", "Author")
                        .WithMany("Forums")
                        .HasForeignKey("AuthorId");
                });

            modelBuilder.Entity("Hood.Models.ForumCategory", b =>
                {
                    b.HasOne("Hood.Models.ForumCategory", "ParentCategory")
                        .WithMany("Children")
                        .HasForeignKey("ParentCategoryId");
                });

            modelBuilder.Entity("Hood.Models.ForumCategoryJoin", b =>
                {
                    b.HasOne("Hood.Models.ForumCategory", "Category")
                        .WithMany("Forum")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Hood.Models.Forum", "Forum")
                        .WithMany("Categories")
                        .HasForeignKey("ForumId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Hood.Models.Log", b =>
                {
                    b.HasOne("Hood.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Hood.Models.MediaDirectory", b =>
                {
                    b.HasOne("Hood.Models.MediaDirectory", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Hood.Models.MediaObject", b =>
                {
                    b.HasOne("Hood.Models.MediaDirectory", "Directory")
                        .WithMany("Media")
                        .HasForeignKey("DirectoryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Hood.Models.Post", b =>
                {
                    b.HasOne("Hood.Models.ApplicationUser", "Author")
                        .WithMany("Posts")
                        .HasForeignKey("AuthorId");

                    b.HasOne("Hood.Models.ApplicationUser", "DeletedBy")
                        .WithMany("DeletedPosts")
                        .HasForeignKey("DeletedById");

                    b.HasOne("Hood.Models.ApplicationUser", "EditedBy")
                        .WithMany("EditedPosts")
                        .HasForeignKey("EditedById");

                    b.HasOne("Hood.Models.Post", "Reply")
                        .WithMany()
                        .HasForeignKey("ReplyId");

                    b.HasOne("Hood.Models.Topic", "Topic")
                        .WithMany("Posts")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Hood.Models.PropertyFloorplan", b =>
                {
                    b.HasOne("Hood.Models.PropertyListing", "Property")
                        .WithMany("FloorPlans")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Hood.Models.PropertyListing", b =>
                {
                    b.HasOne("Hood.Models.ApplicationUser", "Agent")
                        .WithMany("Properties")
                        .HasForeignKey("AgentId");
                });

            modelBuilder.Entity("Hood.Models.PropertyMedia", b =>
                {
                    b.HasOne("Hood.Models.PropertyListing", "Property")
                        .WithMany("Media")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Hood.Models.PropertyMeta", b =>
                {
                    b.HasOne("Hood.Models.PropertyListing", "Property")
                        .WithMany("Metadata")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Hood.Models.Subscription", b =>
                {
                    b.HasOne("Hood.Models.SubscriptionProduct", "SubscriptionProduct")
                        .WithMany("Subscriptions")
                        .HasForeignKey("SubscriptionProductId");
                });

            modelBuilder.Entity("Hood.Models.SubscriptionFeature", b =>
                {
                    b.HasOne("Hood.Models.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Hood.Models.Topic", b =>
                {
                    b.HasOne("Hood.Models.ApplicationUser", "Author")
                        .WithMany("Topics")
                        .HasForeignKey("AuthorId");

                    b.HasOne("Hood.Models.Forum", "Forum")
                        .WithMany("Topics")
                        .HasForeignKey("ForumId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Hood.Models.UserAccessCode", b =>
                {
                    b.HasOne("Hood.Models.ApplicationUser", "User")
                        .WithMany("AccessCodes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Hood.Models.UserSubscription", b =>
                {
                    b.HasOne("Hood.Models.Subscription", "Subscription")
                        .WithMany("Users")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Hood.Models.ApplicationUser", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Hood.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Hood.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Hood.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Hood.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
