<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Hood</AssemblyName>
    <PackageId>Hood</PackageId>
    <Description>Complete Hood CMS Package, includes all default controllers for basic setup, packaged with the Bootstrap 4 default theme.</Description>
    <OutputType>Library</OutputType>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Hood.Core\Hood.Core.csproj" />
    <ProjectReference Include="..\Hood.Admin\Hood.Admin.csproj" />
    <ProjectReference Include="..\Hood.UI.Core\Hood.UI.Core.csproj" />
  </ItemGroup>
</Project>
