<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Hood.UI.Admin</AssemblyName>
    <PackageId>Hood.UI.Admin</PackageId>
    <OutputType>Library</OutputType>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="node_modules\**" />
    <EmbeddedResource Remove="node_modules\**" />
    <None Remove="node_modules\**" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Areas\**\*.cshtml" />
    <EmbeddedResource Include="Areas\**\*.json" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Hood.Core\Hood.Core.csproj" />
  </ItemGroup>
</Project>
