<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Hood.Admin</AssemblyName>
    <PackageId>Hood.Admin</PackageId>
    <OutputType>Library</OutputType>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Hood.Core\Hood.Core.csproj" />
    <ProjectReference Include="..\Hood.UI.Admin\Hood.UI.Admin.csproj" />
  </ItemGroup>
</Project>
